services:
  notification-service:
    build:
      context: .
      target: runner
    image: notification-service:latest
    container_name: notification-service
    env_file:
      - .env
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:19092
      - SERVER_PORT=4008
      - MAILTRAP_KEY=${MAILTRAP_KEY}
      - SPRING_MAIL_HOST=smtp.mailtrap.io
      - SPRING_MAIL_PORT=2525
      - SPRING_MAIL_USERNAME=90df63bf3c4032
      - SPRING_MAIL_PASSWORD=9e1f5d30a6bfd9
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
      - SPRING_MAIL_PROPERTIES_MAIL_DEBUG=true
    ports:
      - "4008:4008"
    networks:
      - internal

networks:
  internal:
    external: true


