spring.application.name=notification-service


spring.kafka.bootstrap-servers=kafka:19092

spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.properties.spring.json.use.type.headers=false

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer


#spring.mail.host=smtp.mailtrap.io
#spring.mail.port=2525
#spring.mail.username=90df63bf3c4032
#spring.mail.password=9e1f5d30a6bfd9
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true