global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth-service:4005']

  - job_name: 'product-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['product-catalog-service:4004']

  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['payment-service:4007']

  - job_name: 'shopping-cart-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'shopping-cart-service:4006' ]

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:4008']