server:
  port: 4000

spring:
  data:
    redis:
      host: redis
      port: 6379
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20

          routes:
            - id: auth-public-route
              uri: http://auth-service:4005
              predicates:
                - Path=/api/v1/auth/login, /api/v1/auth/register, /api/v1/auth/verify-account,
                  /api/v1/auth/reset-password/**

            - id: auth-private-route
              uri: http://auth-service:4005
              predicates:
                - Path=/api/v1/auth/user/**, /api/v1/auth/all, /api/v1/auth/validate, /api/v1/address/**
              filters:
                - JwtValidation

            - id: auth-swagger-route
              uri: http://auth-service:4005
              predicates:
                - Path=/auth/v3/api-docs/**
              filters:
                - RewritePath=/auth/(?<segment>.*), /$\{segment}

            - id: product-public-read-routes
              uri: http://product-catalog-service:4004
              predicates:
                - Path=/api/v1/product/**, /api/v1/categories/all
                - Method=GET

            - id: product-private-write-routes
              uri: http://product-catalog-service:4004
              predicates:
                - Path=/api/v1/product/**
                - Method=POST, PUT, DELETE
              filters:
                - name: JwtValidation

            - id: product-service-swagger-route
              uri: http://product-catalog-service:4004
              predicates:
                - Path=/product/v3/api-docs/**
              filters:
                - RewritePath=/product/(?<segment>.*), /$\{segment}

            - id: categories-route
              uri: http://product-catalog-service:4004
              predicates:
                - Path=/api/v1/categories/**
              filters:
                - JwtValidation

            - id: shopping-cart-service-route
              uri: http://shopping-cart-service:4006
              predicates:
                - Path=/api/v1/cart/**
              filters:
                - JwtValidation

            - id: shopping-cart-service-swagger-route
              uri: http://shopping-cart-service:4006
              predicates:
                - Path=/cart/v3/api-docs/**
              filters:
                - RewritePath=/cart/(?<segment>.*), /$\{segment}

            - id: payment-service-route
              uri: http://payment-service:4007
              predicates:
                - Path=/api/v1/payment/**
              filters:
                - JwtValidation

            - id: payment-service-swagger-route
              uri: http://payment-service:4007
              predicates:
                - Path=/payment/v3/api-docs/**
              filters:
                - RewritePath=/payment/(?<segment>.*), /$\{segment}

            - id: orders-service-route
              uri: http://orders-service:4009
              predicates:
                - Path=/api/v1/orders/**
              filters:
                - JwtValidation

            - id: orders-service-swagger-route
              uri: http://orders-service:4009
              predicates:
                - Path=/orders/v3/api-docs/**
              filters:
                - RewritePath=/orders/(?<segment>.*), /$\{segment}

            - id: notification-service-route
              uri: http://notification-service:4008
              predicates:
                - Path=/api/notification/**
              filters:
                - JwtValidation

springdoc:
  swagger-ui:
    path: /swagger
    use-root-path: true
    urls:
      - name: Auth Service
        url: /auth/v3/api-docs
      - name: Product Catalog Service
        url: /product/v3/api-docs
      - name: Cart Shopping Service
        url: /cart/v3/api-docs
      - name: Payment Service
        url: /payment/v3/api-docs
      - name: Order Service
        url: /orders/v3/api-docs
  api-docs:
    enabled: true