spring.application.name=payment-service

spring.kafka.bootstrap-servers=kafka:19092


spring.kafka.consumer.auto-offset-reset=latest

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer